/**
 * Copyright 1999-2016 Carsten Friedrich (Carsten.Friedrich@gmail.com)
 * Contributions by Falk Schreiber, Francois Bertault, Damian Merrick, and probably others
 * License: GNU GENERAL PUBLIC LICENSE 3.0 (https://www.gnu.org/copyleft/gpl.html)
 *
 */
/* Generated By:JavaCC: Do not edit this line. ProteinParserConstants.java */
package org.carsten.ProteinExplorer;

public interface ProteinParserConstants {

	int EOF = 0;
	int NL = 3;
	int STRING = 4;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "<NL>", "<STRING>", };

}
