/**
 * Copyright 1999-2016 Carsten Friedrich (Carsten.Friedrich@gmail.com)
 * Contributions by Falk Schreiber, Francois Bertault, Damian Merrick, and probably others
 * License: GNU GENERAL PUBLIC LICENSE 3.0 (https://www.gnu.org/copyleft/gpl.html)
 *
 */
/* Generated By:JavaCC: Do not edit this line. GraphedParserConstants.java */
package org.carsten.jjgraph.graph;

public interface GraphedParserConstants {

	int EOF = 0;
	int NUM = 6;
	int STRING = 7;
	int START_COMMENT = 8;
	int END_COMMENT = 9;
	int GRAPH = 10;
	int DIRECTION = 11;
	int FF_C = 12;
	int FF_3D = 13;
	int JJ_HIDDEN = 14;
	int JJ_APP = 15;
	int NP = 16;
	int JCOLOR = 17;
	int FF_WE = 18;
	int END = 19;
	int WORD = 20;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"=\"", "<NUM>", "<STRING>", "\"{$\"",
			"\"$}\"", "\"GRAPH\"", "<DIRECTION>", "<FF_C>", "\"FF_3D\"", "\"JJ_HIDDEN\"", "\"JJ_APP\"", "\"NP\"",
			"\"JCOLOR\"", "\"FF_WE\"", "\"END\"", "<WORD>", "\";\"", };

}
