/**
 * Copyright 1999-2016 Carsten Friedrich (Carsten.Friedrich@gmail.com)
 * Contributions by Falk Schreiber, Francois Bertault, Damian Merrick, and probably others
 * License: GNU GENERAL PUBLIC LICENSE 3.0 (https://www.gnu.org/copyleft/gpl.html)
 *
 */
/* Generated By:JavaCC: Do not edit this line. JJDotParserConstants.java */
package org.carsten.jjgraph.graph;

public interface JJDotParserConstants {

	int EOF = 0;
	int NUM = 5;
	int STRING = 6;
	int START_COMMENT = 7;
	int END_COMMENT = 8;
	int GRAPH = 9;
	int END = 10;
	int WORD = 11;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "<NUM>", "<STRING>", "\"[\"", "\"]\"",
			"<GRAPH>", "\"}\"", "<WORD>", "\"{\"", "\"=\"", "\",\"", "\";\"", "\"->\"", };

}
