/**
 * Copyright 1999-2016 Carsten Friedrich (Carsten.Friedrich@gmail.com)
 * Contributions by Falk Schreiber, Francois Bertault, Damian Merrick, and probably others
 * License: GNU GENERAL PUBLIC LICENSE 3.0 (https://www.gnu.org/copyleft/gpl.html)
 *
 */
/* Generated By:JavaCC: Do not edit this line. MatrixMarketParserConstants.java */
package org.carsten.jjgraph.graph;

public interface MatrixMarketParserConstants {

	int EOF = 0;
	int NUM = 6;
	int FIRSTLINE = 7;
	int FLOAT = 8;
	int WORD = 9;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"=\"", "<NUM>", "\"%%MatrixMarket\"",
			"<FLOAT>", "<WORD>", };

}
